// Cloudflare Pages customer shell for EMPEROR FOODS.
const APP_ORIGIN = "https://emperor-foods.vatisp.chatgpt.site";
const DUCK_LOGO = "https://raw.githubusercontent.com/ThomasHIP/emperor-foods/main/cloudflare-pages/emperor-duck-logo.svg";

const CUSTOMER_SHELL = `<!doctype html>
<html lang="th">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>EMPEROR FOODS | Emperor Duck เป็ดจักรพรรดิ</title>
<meta name="description" content="EMPEROR DUCK — ค่าส่งแช่เย็น ทั่วไทย 200 บาท รับ 200 เครดิต">
<meta name="theme-color" content="#f8f0df">
<style>
:root{--cream:#f8f0df;--wine:#6b1020;--wine-deep:#310611;--gold:#c99b32;--ink:#2c1820;--header-h:132px}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;background:var(--cream);overflow:hidden}body{font-family:Arial,Helvetica,"Noto Sans Thai",sans-serif}
.app-frame{position:fixed;left:0;right:0;bottom:0;top:var(--header-h);width:100%;height:calc(100dvh - var(--header-h));border:0;background:var(--cream);opacity:0;transform:scale(1.006);transition:opacity .7s ease,transform 1s ease}.app-frame.is-ready{opacity:1;transform:none}
.duck-header{position:fixed;z-index:20;top:0;left:0;right:0;height:var(--header-h);display:grid;place-items:center;overflow:hidden;background:radial-gradient(circle at 50% 40%,#fffdf7 0%,#fbf4e7 58%,#f2e5cd 100%);border-bottom:1px solid rgba(201,155,50,.28);box-shadow:0 8px 28px rgba(65,20,20,.06)}
.duck-logo{display:block;width:min(88vw,430px);height:118px;object-fit:contain;filter:drop-shadow(0 4px 12px rgba(67,20,20,.08))}
.menu-toggle{position:fixed;z-index:22;right:12px;bottom:max(12px,env(safe-area-inset-bottom));max-width:calc(100vw - 24px);border:1px solid rgba(255,255,255,.34);border-radius:22px;padding:10px 16px;background:linear-gradient(135deg,#5c0617,#8b1830);color:#fff8e9;box-shadow:0 10px 30px rgba(35,0,9,.28);font-weight:800;font-size:14px;line-height:1.35;text-align:center;cursor:pointer}.menu-toggle strong{display:block;color:#f3cf77;font-size:16px}
.menu-backdrop{position:fixed;z-index:23;inset:0;background:rgba(18,3,8,.52);opacity:0;visibility:hidden;transition:.25s ease}.menu-backdrop.is-open{opacity:1;visibility:visible}
.menu-drawer{position:fixed;z-index:24;top:0;right:0;width:min(92vw,430px);height:100dvh;background:#fffaf0;color:var(--ink);box-shadow:-22px 0 60px rgba(31,0,9,.3);transform:translateX(103%);transition:transform .32s cubic-bezier(.2,.8,.2,1);overflow:auto;padding:22px 20px calc(34px + env(safe-area-inset-bottom))}.menu-drawer.is-open{transform:none}
.menu-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding-bottom:14px;border-bottom:1px solid #eadcc5}.menu-head small{display:block;color:#8d6d4d;font-weight:700;letter-spacing:.08em;margin-bottom:4px}.menu-head h2{margin:0;color:var(--wine-deep);font:700 27px/1.05 Georgia,serif}.close-menu{border:1px solid #e2d3bb;background:#fff;color:var(--wine);border-radius:50%;width:38px;height:38px;font-size:22px;cursor:pointer}
.delivery-card,.benefit-card{margin:14px 0;padding:14px 15px;border-radius:14px;line-height:1.5}.delivery-card{border:1px solid #dfbd66;background:linear-gradient(135deg,#fff3c9,#fff9e8);color:#5d3207}.benefit-card{border:1px solid #f0b3c1;background:linear-gradient(135deg,#fff0f5,#f3f7ff);color:#4d2130}.delivery-card b,.benefit-card b{font-size:20px;color:#851426}
.menu-list{display:grid;border-top:1px solid #eadcc5}.menu-row{display:grid;grid-template-columns:1fr auto;gap:14px;padding:13px 2px;border-bottom:1px solid #eadcc5}.menu-row b{font-size:15px}.menu-row small{display:block;margin-top:3px;color:#816f67;line-height:1.4}.menu-price{color:#8a1023;font:700 20px/1 Georgia,serif;white-space:nowrap}.menu-note{margin-top:16px;color:#76625b;font-size:12px;line-height:1.55}
.intro{position:fixed;z-index:30;inset:0;display:grid;place-items:center;overflow:hidden;background:radial-gradient(circle at 50% 44%,rgba(234,212,154,.28),transparent 30%),linear-gradient(145deg,#fffaf0 0%,#f8f0df 52%,#f2e5cc 100%);color:var(--wine);transition:opacity .85s ease,visibility .85s ease}.intro::after{content:"";position:absolute;left:-35%;top:0;width:28%;height:100%;background:linear-gradient(90deg,transparent,rgba(255,255,255,.72),transparent);transform:skewX(-18deg);animation:lightSweep 2.7s .35s cubic-bezier(.22,.7,.24,1) both}.intro.is-leaving{opacity:0;visibility:hidden;pointer-events:none}
.intro-lockup{position:relative;width:min(78vw,560px);display:grid;place-items:center;text-align:center}.crown{margin-bottom:18px;color:var(--gold);font:400 clamp(37px,8vw,61px)/1 Georgia,serif;opacity:0;transform:translateY(-18px) scale(.82);animation:crownIn .85s .15s cubic-bezier(.2,.8,.2,1.2) forwards}.word-emperor{margin:0;color:var(--wine-deep);font:400 clamp(33px,8.8vw,73px)/1 Georgia,serif;letter-spacing:.2em;text-indent:.2em;opacity:0;filter:blur(7px);transform:scale(.96);animation:wordIn 1s .58s ease forwards}.word-foods{margin:14px 0 0;color:var(--wine);font-weight:700;font-size:clamp(11px,2.8vw,17px);letter-spacing:.72em;text-indent:.72em;opacity:0;transform:translateY(9px);animation:foodsIn .75s 1.05s ease forwards}.rule{width:min(64vw,390px);height:1px;margin-top:28px;background:linear-gradient(90deg,transparent,var(--gold),transparent);transform:scaleX(0);animation:ruleIn .85s 1.18s ease forwards}.tagline{margin:17px 0 0;color:#816e5f;font-size:clamp(8px,2vw,11px);font-weight:600;letter-spacing:.22em;text-transform:uppercase;opacity:0;animation:foodsIn .7s 1.45s ease forwards}
.fallback{position:fixed;z-index:31;left:50%;bottom:max(22px,env(safe-area-inset-bottom));transform:translateX(-50%);color:var(--wine);font-size:11px;opacity:0;transition:.3s}.fallback.is-visible{opacity:.72}
@keyframes crownIn{to{opacity:1;transform:none}}@keyframes wordIn{to{opacity:1;filter:blur(0);transform:none}}@keyframes foodsIn{to{opacity:1;transform:none}}@keyframes ruleIn{to{transform:scaleX(1)}}@keyframes lightSweep{0%{transform:translateX(0) skewX(-18deg);opacity:0}18%{opacity:.55}100%{transform:translateX(620%) skewX(-18deg);opacity:0}}
@media(max-width:600px){:root{--header-h:112px}.duck-logo{width:min(92vw,360px);height:100px}.menu-toggle{font-size:13px;padding:9px 14px}.menu-toggle strong{font-size:15px}}@media(prefers-reduced-motion:reduce){.intro::after{display:none}}
</style>
</head>
<body>
<header class="duck-header" aria-label="Emperor Duck"><img class="duck-logo" src="${DUCK_LOGO}" alt="Emperor Duck เป็ดจักรพรรดิ"></header>
<iframe id="emperor-app" class="app-frame" title="EMPEROR FOODS online ordering" src="${APP_ORIGIN}/" allow="payment *; clipboard-write" referrerpolicy="strict-origin-when-cross-origin"></iframe>
<button id="menu-toggle" class="menu-toggle" type="button" aria-controls="current-menu" aria-expanded="false"><span>ค่าส่งแช่เย็น ทั่วไทย 200 บาท</span><strong>รับ 200 เครดิต</strong></button>
<div id="menu-backdrop" class="menu-backdrop" aria-hidden="true"></div>
<aside id="current-menu" class="menu-drawer" aria-label="Emperor Duck current menu" aria-hidden="true">
<div class="menu-head"><div><small>EMPEROR DUCK · CURRENT MENU</small><h2>เมนูและราคาปัจจุบัน</h2></div><button id="close-menu" class="close-menu" type="button" aria-label="Close menu">×</button></div>
<div class="delivery-card"><b>ค่าส่งแช่เย็น ทั่วไทย 200 บาท</b><br><small>Chilled delivery nationwide · flat rate 200 Baht</small></div>
<div class="benefit-card"><b>รับ 200 เครดิต</b><br><small>Receive 200 Credits</small></div>
<div class="menu-list">
<div class="menu-row"><div><b>เป็ดรมควัน อบชานอ้อย</b><small>Whole Smoked Duck</small></div><div class="menu-price">฿790</div></div>
<div class="menu-row"><div><b>อกเป็ดรมควัน</b><small>Smoked Duck Breast · 1 ชิ้น</small></div><div class="menu-price">฿169</div></div>
<div class="menu-row"><div><b>อกเป็ดรมควัน Family Pack</b><small>Smoked Duck Breast · 4 ชิ้น</small></div><div class="menu-price">฿590</div></div>
<div class="menu-row"><div><b>น่องสะโพกเป็ดรมควัน</b><small>Smoked Duck Thigh</small></div><div class="menu-price">฿189</div></div>
<div class="menu-row"><div><b>หมูรมควัน</b><small>Smoked Pork</small></div><div class="menu-price">฿429</div></div>
<div class="menu-row"><div><b>คอหมูรมควัน</b><small>Smoked Pork Neck</small></div><div class="menu-price">฿479</div></div>
<div class="menu-row"><div><b>ลิ้นหมูรมควัน</b><small>Smoked Pig’s Tongue · ประมาณ 330 กรัม</small></div><div class="menu-price">฿490</div></div>
<div class="menu-row"><div><b>ชุดสามกษัตริย์</b><small>อกเป็ดรมควัน 1 + หมูรมควัน 1 + สามชั้นรมควัน 1 · ประมาณ 500 กรัม</small></div><div class="menu-price">฿490</div></div>
</div><p class="menu-note">ค่าส่งแช่เย็น ทั่วไทย 200 บาท · รับ 200 เครดิต</p></aside>
<section id="emperor-intro" class="intro" aria-label="EMPEROR FOODS introduction"><div class="intro-lockup"><div class="crown" aria-hidden="true">♛</div><h1 class="word-emperor">EMPEROR</h1><p class="word-foods">FOODS</p><div class="rule"></div><p class="tagline">Premium Asian Lifestyle</p></div></section>
<a id="fallback" class="fallback" href="${APP_ORIGIN}/">Open EMPEROR FOODS</a>
<script>(()=>{const frame=document.getElementById("emperor-app"),intro=document.getElementById("emperor-intro"),fallback=document.getElementById("fallback"),toggle=document.getElementById("menu-toggle"),drawer=document.getElementById("current-menu"),backdrop=document.getElementById("menu-backdrop"),close=document.getElementById("close-menu"),startedAt=performance.now(),reduceMotion=matchMedia("(prefers-reduced-motion: reduce)").matches,minimumIntro=reduceMotion?450:2800;let revealed=false;const revealApp=()=>{if(revealed)return;revealed=true;frame.classList.add("is-ready");intro.classList.add("is-leaving");setTimeout(()=>intro.remove(),reduceMotion?350:950)};const setMenu=open=>{drawer.classList.toggle("is-open",open);backdrop.classList.toggle("is-open",open);drawer.setAttribute("aria-hidden",String(!open));backdrop.setAttribute("aria-hidden",String(!open));toggle.setAttribute("aria-expanded",String(open))};toggle.addEventListener("click",()=>setMenu(!drawer.classList.contains("is-open")));close.addEventListener("click",()=>setMenu(false));backdrop.addEventListener("click",()=>setMenu(false));document.addEventListener("keydown",e=>{if(e.key==="Escape")setMenu(false)});frame.addEventListener("load",()=>{const remaining=Math.max(0,minimumIntro-(performance.now()-startedAt));setTimeout(revealApp,remaining)},{once:true});setTimeout(()=>fallback.classList.add("is-visible"),6500)})();</script>
</body></html>`;

function rewriteLocation(value, publicOrigin) { if (!value) return value; return value.replace(APP_ORIGIN, publicOrigin); }
export default { async fetch(request) { const publicUrl=new URL(request.url); const acceptsHtml=(request.headers.get("accept")||"").includes("text/html"); if(request.method==="GET"&&publicUrl.pathname==="/"&&acceptsHtml){return new Response(CUSTOMER_SHELL,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","content-security-policy":`frame-src ${APP_ORIGIN}; default-src 'self'; img-src https://raw.githubusercontent.com; style-src 'unsafe-inline'; script-src 'unsafe-inline'`,"x-content-type-options":"nosniff"}})} const upstreamUrl=new URL(publicUrl.pathname+publicUrl.search,APP_ORIGIN); const headers=new Headers(request.headers); headers.delete("host"); headers.set("x-forwarded-host",publicUrl.host); headers.set("x-forwarded-proto","https"); const upstreamResponse=await fetch(new Request(upstreamUrl,{method:request.method,headers,body:request.method==="GET"||request.method==="HEAD"?undefined:request.body,redirect:"manual"})); const responseHeaders=new Headers(upstreamResponse.headers); const location=responseHeaders.get("location"); if(location)responseHeaders.set("location",rewriteLocation(location,publicUrl.origin)); return new Response(upstreamResponse.body,{status:upstreamResponse.status,statusText:upstreamResponse.statusText,headers:responseHeaders}); } };